Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-20.04"
  
  config.vm.hostname = "ubuntu2004-sandbox"
  config.vm.network "private_network", ip: "192.168.33.12", netmask: "255.255.255.0"
  config.vm.synced_folder ".", "/vagrant"
  
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 4096
    vb.name = "ubuntu2004-sandbox"
  end
  
  config.vm.provision "shell", path: "provision/bootstrap.sh"

end
