Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-20.04"
  
  config.vm.hostname = "devbox"
  config.vm.network "private_network", ip: "192.168.33.11", netmask: "255.255.255.0"
  
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 4096
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
  SHELL

end
